---
title: shreddit
timezone: Australia/Brisbane
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  gallery:
    title: Gallery
    output: true
  home:
    title: Home
    output: true
exclude:
    - node_modules
description: |
  Shreddit! where skaters of all kinds coexist and challenege eachother to bring skating as a whole to the next level!
baseurl: 
url: https://www.shreddit.com
github_username: FinnVoid
markdown: kramdown
